### ISSUE TITLE
Settings for cloner

### ISSUE THREAD

**Issue by IgorMamushin** [marcelltoth/ObjectCloner#3]
Hi again :).
I have 1 more feature.
Is it possible do settings for this cloner?

We need 2 things:
1. Don't clone private fields and properties.
2. Ignore some properties. (Usually for ignore property used attributes. It will be well if we can set our ignore attribute, for example "JsonIgnore")

I did it in my fork. It is worked. But i did it wrong, it broke design.

**Comment by marcelltoth** [comment]
Hi Igor,

Let me break this into two different issues, so we can discuss them separately.
